name: docs

on:
  push:
    branches: [ master, add-manual-doc ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: './src/'

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.13.0'
      - run: go version

      - name: generate markdown and concatenate
        run: |
          cd src/pkg/sdk
          go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
          gomarkdoc api.go > doc.md -u
          
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: './web/'

      - name: promote
        run: |
          cd web
          cp ../src/pkg/sdk/doc.md index.md
          
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'publish generated docs'
          add: 'index.md'
          cwd: './web/'
          author_name: 'Relay Pro builder'
          author_email: 'info@relaypro.com'
          push: true